import { AnswerInfo } from "./grade";

const answers: AnswerInfo[] = [
    {answer: "switches the places of the first and last elements of the list with each other",correct: 1},
    {answer: "sets first value of list x equal to its last value and last value of list x equal to first value ",correct: 1},
    {answer: "Swaps the first and last value of a list for each other",correct: 1},
    {answer: "flips the position of the first and last elements of a list",correct: 1},
    {answer: "the first and last element in the list switch places",correct: 1},
    {answer: "the first and last value of the list is swapped",correct: 1},
    {answer: "switch the first and last item in a list",correct: 1},
    {answer: "The first and last variables of a list are switched.",correct: 1},
    {answer: "swap the values of the first and last elements of a list",correct: 1},
    {answer: "Switches the first element in the list with the last element in the same list",correct: 1},
    {answer: "The code swaps the first and last element around in a list.",correct: 1},
    {answer: "switches the first and last element of the list",correct: 1},
    {answer: "switches the first and last element",correct: 1},
    {answer: "Switch the places of the first and last entries within a specified list.",correct: 1},
    {answer: "switch first item in list with last item in list",correct: 1},
    {answer: "The first element of x and the last element of x trade locations",correct: 1},
    {answer: "exchange the first and the last element in the list",correct: 1},
    {answer: "The first and last items in list x are being swapped with each other",correct: 1},
    {answer: "switch the first index and last index of given list",correct: 1},
    {answer: "switches the values of the first and last items in list",correct: 1},
    {answer: "swaps the first and last elements of the list, x",correct: 1},
    {answer: "Switching the first and last variables in a list.",correct: 1},
    {answer: "Defines a function that switches the first and last value of a list",correct: 1},
    {answer: "Switches the first and last element of a list",correct: 1},
    {answer: "switches the first and last elements in a list",correct: 1},
    {answer: "switches the last and first value in a list",correct: 1},
    {answer: "Switches the first and last value of the list",correct: 1},
    {answer: "exchange the value of first and the last variable in the list x",correct: 1},
    {answer: "switches the first and last elements in a list",correct: 1},
    {answer: "z is assigned to the first element in x, the first and last element of x switch values",correct: 1},
    {answer: "switches the values between the first value and last value of list x",correct: 1},
    {answer: "switches/interchanges the positions of the first and last elements in a list",correct: 1},
    {answer: "the first value in list x is changed to be the same value as the last value in list x, the last value in list x is then changed to be the initial first value in list x ",correct: 1},
    {answer: "switches the first and last numbers in list x ",correct: 1},
    {answer: "Swaps the first and last elements in a list",correct: 1},
    {answer: "swaps the first and last item in a list",correct: 1},
    {answer: "Interchanging first and last elements of a list",correct: 1},
    {answer: "the first and last elements of a list swap values",correct: 1},
    {answer: "change the position of the first element and the last element",correct: 1},
    {answer: "the first and last values in a list are flipped",correct: 1},
    {answer: "switches the values of the first and last elements in the list. EX: if x=[5,10,15] after the program x= [15,10,5]",correct: 1},
    {answer: "Swaps the last value of a list with its first value",correct: 1},
    {answer: "switches the first and last element of a list",correct: 1},
    {answer: "switches the first and last elements in a list",correct: 1},
    {answer: "The first and last element in a list swap positions.",correct: 1},
    {answer: "exchange the first element and the last element in the list x",correct: 1},
    {answer: "Switches the last element within a list with the first element",correct: 1},
    {answer: "Switches the values of the first and last element of list x.",correct: 1},
    {answer: "switches the first value and the last value in a list",correct: 1},
    {answer: "reversed the last element in the list to the first element in the list, and the last element to the first element",correct: 1},
    {answer: "The function will return True if the index 0 element of x is the same as the index -1 element of x because this means that z will also be equal to the index -1 element of x since z is equal to the index 0 element of x",correct: 0},
    {answer: "Defines a variable z using elements of a list x",correct: 0},
    {answer: "assigns the z variable to the index of x[-1]",correct: 0},
    {answer: "assigning a variable to the last value of a list",correct: 0},
    {answer: "returns True",correct: 0},
    {answer: "computes the value of z at index of -1 of x",correct: 0},
    {answer: "swaps the value of two elements in a list",correct: 0},
    {answer: "Defines a function with variable x, a list. Then it assigns the first value to z and after replaces the first value with the last value and finally assigns the last value to z.",correct: 0},
    {answer: "this function showcases how z is equal to x{0}. x{0} is equal to x{-1}. Therefore, x{-1} is equal to z",correct: 0},
    {answer: "the variable z is in the list x",correct: 0},
    {answer: "sets the last element in list x equal to the value of the first element ",correct: 0},
    {answer: "evaluates that lists corresponds",correct: 0},
    {answer: "changes the indexing of a list",correct: 0},
    {answer: "The first and last elements in a list are equivalent.",correct: 0},
    {answer: "the last element of the list is equal to the first element of the list",correct: 0},
    {answer: "The first and last indexes of a list are the same",correct: 0},
    {answer: "function swaps the first value of a list with the last value of a list and stores it in z",correct: 0},
    {answer: "The function switches the order of two numbers in the list",correct: 0},
    {answer: "checks to see if list x is one element long",correct: 0},
    {answer: "swaps the order of two elements in a list",correct: 0},
    {answer: "makes the last value of a list and a first value of a list equal and then assigns it to a variable",correct: 0},
    {answer: "both the first and last elements of the list are equal",correct: 0},
    {answer: "returns True if the last value in a list is equal to value of z. ",correct: 0},
    {answer: "integer is equal to z",correct: 0},
    {answer: "Setting the variable z equal to index zero in list x. Changing index zero to negative one index. Then changing index negative one to what index zero equals.",correct: 0},
    {answer: "The variable is set equal to the first element of a list, which is set equal to the last element of the list. ",correct: 0},
    {answer: "reassigns value at index -1 to z",correct: 0},
    {answer: "find out if the variables are the same as in the list.",correct: 0},
    {answer: "the variables are assigned a value from the expression and they change with every new lines subject to their new assigned spot",correct: 0},
    {answer: "Assigns the last element in list x to be the first element in the list",correct: 0},
    {answer: "The program equates the value of z to the last index value of x.",correct: 0},
    {answer: "The beginning and end of a list are the same value.",correct: 0},
    {answer: "Final index of list x gains value of first index of list x",correct: 0},
    {answer: "Comparing two values equal to a variable",correct: 0},
    {answer: "replaces an element in the list with another elements",correct: 0},
    {answer: "Checks if the last unit of x is z",correct: 0},
    {answer: "check if the first and last elements of a list are the same ",correct: 0},
    {answer: "returns the value of z after each code",correct: 0},
    {answer: "the first and second to last value in the given list become equal and are assigned to the variable z ",correct: 0},
    {answer: "the value in a list at the index of -1 of x is equal to z",correct: 0},
    {answer: "the first and last elements in the list x are the same ",correct: 0},
    {answer: "Makes the first element and the last element of a list the same value.",correct: 0},
    {answer: "make the start and the end of list equal to each other, and store the value in z again.",correct: 0},
    {answer: "The elements in the list swap positions",correct: 0},
    {answer: "Assigns z to the last element of list x",correct: 0},
    {answer: "first item in the list is inputted into variable",correct: 0},
    {answer: "the first and last element of a list are equal to each other ",correct: 0},
    {answer: "assigns z to a value in the list x",correct: 0},
    {answer: "compute that the last character of f(x) is z(also the first alphabet of f(x) is z) ",correct: 0},
    {answer: "variable z is equivalent to the second to last index of x",correct: 0},
]

export const answersData = [...answers];